### ISSUE TITLE
models for 3d printed case

### ISSUE THREAD

**Issue by kkatee** [Pixelcontroller/f-test_issues#6]
Would it be possible to get the model files for the 3d printed case?

Thinking about some mods for my ftest and it would be easier to work from the existing case files rather than starting over :D

Thanks

**Comment by dpitts** [comment]
Hi

We buy the cases from a vendor and he owns the models.


Thank you,

David Pitts

On Oct 19, 2024 6:33 PM, kkatee ***@***.***> wrote:

Would it be possible to get the model files for the 3d printed case?

Thinking about some mods for my ftest and it would be easier to work from the existing case files rather than starting over :D

Thanks
